# Set maximum value of wanted level.
max-level: 5
# Set amount of wanted level increase.
level:
  player: 1
  mob: 0.2
  chat: 0.3
  item: 0.5
# Set illegal words.
words:
# Set illegal items.
items:
  - flint_and_steel
  - tnt
  - lava_bucket
# Set wanted time in seconds.
wanted-time: 60
# Enable mob spawning.
spawn: true
# Set spawning mobs.
mobs:
  day:
    - creeper
    - enderman
    - spider
    - witch
    - slime
  night:
    - creeper
    - enderman
    - spider
    - witch
    - slime
    - zombie
    - skeleton
# Set range where mobs spawn.
range: 20
# Set offset of spawn range.
offset: 10
# Set limit on amount of spawn.
limit: 100

# You can write an expression.
# The random is number in range 0 to less than 1.

# Set spawn interval in seconds.
interval: 30 / level
# Set amount of spawn.
amount: level * 2 * (random + 1)
