# Set maximum value of wanted level.
max-level: 5
# Set amount of wanted level increase.
level:
  player: 1
  mob: 0.2
  chat: 0.3
  item: 0.5
# Set illegal words.
words:
# Set illegal items.
items:
  - flint_and_steel
  - tnt
  - lava_bucket
# Enable mob spawning.
spawn: true
# Set spawning mobs.
mobs:
  day:
    - creeper
    - enderman
    - spider
    - witch
    - slime
  night:
    - creeper
    - enderman
    - spider
    - witch
    - slime
    - zombie
    - skeleton
# Set range where mobs spawn.
range: 30
# Set offset of spawn range.
offset: 10
# Set limit on amount of spawn.
limit: 10

# You can write an expression.
# The random is number in range 0 to less than 1.

# Set spawn interval.
interval: 1000 / level
# Set amount of spawn.
amount: level * 5 * (random ^ 2)
