name: Wanted
version: @version@
main: dev.krmn.wanted.Wanted
api-version: 1.15
authors: [ krmn ]
description: KUN GTA Plugin
depend:
  - GTAWantedDisplayTestPlugin
  - VotePlugin

commands:
  wanted:
    usage: |
      /<command> v [start|end]
      /<command> [player] [level]
      /<command> reload config
    description: Change wanted level
    permission: wanted.wanted

permissions:
  wanted.wanted:
    description: Allows you to change wanted level
    default: op